ENV['SPACESHIP_SKIP_2FA_UPGRADE'] = '1'

fastlane_version "2.73.0"

default_platform :ios

platform :ios do
  build_type = "QAConnectMe Build"

  before_all do
    unless ENV["SLACK_CREDENTIAL"].nil?
      ENV["SLACK_URL"] = "https://hooks.slack.com/services/#{ENV["SLACK_CREDENTIAL"]}"
    end
  end

  after_all do |lane|
    unless ENV["SLACK_CREDENTIAL"].nil?
      commit_message = ENV["currentBuild.changeSets"]
      build_number = get_build_number(xcodeproj: "ConnectMe.xcodeproj")
      slack(channel: "connectme_build", message: "#{build_type} ##{build_number} #{commit_message}")
    end
  end

  error do |lane, exception|
    unless ENV["SLACK_CREDENTIAL"].nil?
      msg = exception.to_s
      msg = msg.encode('utf-8', :invalid => :replace, :undef => :replace, :replace => '_')
      payloadMsg = exception.error_info.to_s
      payloadMsg = payloadMsg.encode('utf-8', :invalid => :replace, :undef => :replace, :replace => '_')
      slack(
        channel: "connectme_build",
        message: msg,
        success: false,
        payload: { "Output" => payloadMsg }
      )
    end
  end

  lane :ci do

    cocoapods(
      try_repo_update_on_error: true,
    )

    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

    build(
        match_type: "adhoc",
        compile_type: "adhoc",
        app_identifier: "#{app_identifier}",
    )

  end

  lane :cd do

    remote_branch = git_branch

    cocoapods(
      try_repo_update_on_error: true,
    )

    version_number = project_version_bump

    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

    build(
        match_type: "adhoc",
        compile_type: "adhoc",
        app_identifier: "#{app_identifier}",
    )

    appcenter_token = ENV["APPCENTER_API_TOKEN"]
    UI.user_error!("You didn't set token for AppCenter") if appcenter_token.empty?
    build_type = ENV["BUILD_TYPE"] || "#{build_type}"
    if remote_branch == "main"
      appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "user", app_name: "QA-ConnectMe")
    end

    build(
        match_type: "appstore",
        compile_type: "appstore",
        app_identifier: "#{app_identifier}",
    )

    api_key = app_store_connect_api_key()

    deliver(
      api_key: api_key,
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      run_precheck_before_submit: false
    )
  end

  #==============================================#
  #              PRIVATE LANES                   #
  #==============================================#

  ##### ----- PROJECT_VERSION_BUMP ----- #####
  private_lane :project_version_bump do
    ci_pipeline_id = ENV["CI_PIPELINE_IID"]
    buildNumber = increment_build_number(build_number: ci_pipeline_id, xcodeproj: "ConnectMe.xcodeproj")
    puts 'new build number: ' + buildNumber
    # we are fixing the version number as of now
    # any version number change has to be manual
    version_number = "1.6.2"
    versionNumber = increment_version_number(version_number: version_number, xcodeproj: "ConnectMe.xcodeproj")
    puts 'new version number: ' + versionNumber

    versionNumber.to_s + "-" + buildNumber.to_s
  end

  ##### ----- BUILD ----- #####
  private_lane :build do |options|
    match_certificates(
      type: options[:match_type],
      app_identifier: options[:app_identifier]
    )

    compile(
      type: options[:compile_type],
      app_identifier: options[:app_identifier]
    )
  end

  ##### ----- COMPILE ----- #####
  private_lane :compile do |options|
    types = [ "adhoc", "appstore" ]
    type = options[:type]
    unless types.include? type
        UI.user_error!("Please specify a valid type! " + types.inspect)
    end

    profile = ENV["sigh_#{options[:app_identifier]}_#{type}"]
    disable_automatic_code_signing(path: "ConnectMe.xcodeproj")

    gym(
      scheme: "ConnectMe",
      clean: true
    )
  end

  ##### ----- MATCH_CERTIFICATES ----- #####
  private_lane :match_certificates do |options|

    types = [ "development", "adhoc", "appstore" ]
    type = options[:type]

    unless types.include? type
        UI.user_error!("Please specify a valid type! " + types.inspect)
    end

    match(
      type: "#{type}",
      app_identifier: "#{options[:app_identifier]}",
      force_for_new_devices: true
    )
  end

end
