fastlane_version "2.27.0"

default_platform :android
platform :android do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/#{ENV["SLACK_CREDENTIAL"]}"
end

lane :alpha do
  ci_job_id = ENV["CI_JOB_ID"]
  puts 'gitlab CI build ID: ' + ci_job_id.to_s

  path = '../app/build.gradle'
  reVersionCode = /versionCode\s+(\d+)/
  reVersionName = /versionName\s+(\S+)/
  androidBuildGradleFileContent = File.read(path)
  versionCode = (androidBuildGradleFileContent[reVersionCode, 1].to_i+1)
  ci_build_ref_slug = ENV["CI_BUILD_REF_SLUG"]
  if (ENV["CI_PIPELINE_SOURCE"] == "merge_request") || (ci_build_ref_slug && ci_build_ref_slug != "master")
    versionCode = ci_job_id
  end
  androidBuildGradleFileContent[reVersionCode, 1] = versionCode.to_s

  # Commenting code which increment version number
  # we are keeping version number fixed as of now
  # any change in version number has to be a manual change here

  # versionName = androidBuildGradleFileContent[reVersionName, 1]
  # versionName = versionName.gsub!(/\A"|"\Z/, '')
  # nameArray = versionName.split('.')
  # versionNameMinorNumber = nameArray.pop().to_i+1
  # versionName = nameArray.join('.')
  # newVersionName = "\"" + versionName.to_s + "." + versionNameMinorNumber.to_s + "\""
  newVersionName = "\"1.5.6\""
  puts 'new version number: ' + newVersionName.to_s
  androidBuildGradleFileContent[reVersionName, 1] = newVersionName
  androidBuildGradleFile = File.new(path, 'w')
  androidBuildGradleFile.write(androidBuildGradleFileContent)
  androidBuildGradleFile.close
  gradle(
    task: "assemble",
    build_type: "Release",
  )

  ENV["BUILD_VERSION_CODE"] = versionCode.to_s
  remote_branch = git_branch
  remote_branch = remote_branch.split('/').last

  puts "Current working directory is: " + Dir.pwd
  if remote_branch == "master"
    ENV["BUILD_NAME"] = "QA ConnectMe"
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "QA-MeConnect-Android", file: "app/build/outputs/apk/release/app-armeabi-v7a-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "QA-MeConnect-Android", file: "app/build/outputs/apk/release/app-arm64-v8a-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "QA-MeConnect-Android", file: "app/build/outputs/apk/release/app-x86-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "QA-MeConnect-Android", file: "app/build/outputs/apk/release/app-x86_64-release.apk")
  elsif remote_branch == "stable" || remote_branch == "stage"
    ENV["BUILD_NAME"] = "Stable ConnectMe"
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Stage-MeConnect-Android", file: "app/build/outputs/apk/release/app-armeabi-v7a-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Stage-MeConnect-Android", file: "app/build/outputs/apk/release/app-arm64-v8a-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Stage-MeConnect-Android", file: "app/build/outputs/apk/release/app-x86-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Stage-MeConnect-Android", file: "app/build/outputs/apk/release/app-x86_64-release.apk")
  else
    ENV["BUILD_NAME"] = "Dev ConnectMe"
    ## WARNING ## apk: will be depricated soon (docs already say to use file: but that doesn't work yet.)
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Dev-MeConnect-Android", file: "app/build/outputs/apk/release/app-armeabi-v7a-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Dev-MeConnect-Android", file: "app/build/outputs/apk/release/app-arm64-v8a-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Dev-MeConnect-Android", file: "app/build/outputs/apk/release/app-x86-release.apk")
    appcenter_upload(api_token: ENV["APPCENTER_API_TOKEN"], owner_type: "organization", owner_name: "Evernym-Inc", app_name: "Dev-MeConnect-Android", file: "app/build/outputs/apk/release/app-x86_64-release.apk")
  end

end

  after_all do |lane|
     slack(channel: "connectme_build", message: "#{ENV["BUILD_NAME"]} Android build #{ENV["BUILD_VERSION_CODE"]}")
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end
